{
 model_name : "cl-tohoku/bert-base-japanese-v2",
 device : "cuda",
 seed : 42,
 item : ["story", "title", "keyword"],
 output_hidden_states : true,
 train_dir : "./train_val_split",
 dataset_dir : "../input/nishika-narou",
 model_name : "cl-tohoku/bert-base-japanese-v2",
 pretrained_model_path : "cl-tohoku/bert-base-japanese-v2",
 output_hidden_states : true,
 i8 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 i9 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 i18 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 i41 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 i42 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 i43 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 n86 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 n95 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 n95_01 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 n102 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 n107 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"},
 n117 : { "item_num" : 1, "output_dir" : "i8_inference","model_dir" : "../input/all-model-nishika-narou/n8_model"}
}